# Generated by Django 6.0.4 on 2026-07-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_topiccomment'),
        ('users', '0008_userprofile_xp'),
    ]

    operations = [
    ]
