# Generated by Django 6.0.4 on 2026-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_add_overall_scores_to_judgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='xp_delta_con',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgement',
            name='xp_delta_pro',
            field=models.IntegerField(default=0),
        ),
    ]
