# Generated by Django 6.0.4 on 2026-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_judgement_xp_delta_con_judgement_xp_delta_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
