# Generated by Django 6.0.6 on 2026-07-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0007_topic_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='user_con_disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='user_pro_disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
