# Generated by Django 6.0.6 on 2026-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0008_debate_user_con_disconnected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='con_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='pro_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
