"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv
from project.celery_config import (
    task_queues,
    task_routes,
    task_default_exchange,
    task_default_exchange_type,
    task_default_routing_key,
)

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = list(os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(","))

CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host not in ("localhost", "127.0.0.1")
]


# Application definition
DEFAULT_INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_INSTALLED_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "channels",
]

LOCAL_INSTALLED_APPS = [
    "authentication",
    "quiz",
    "debate",
    "users",
    "news",
]

INSTALLED_APPS = [
    *DEFAULT_INSTALLED_APPS,
    *THIRD_PARTY_INSTALLED_APPS,
    *LOCAL_INSTALLED_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "base.middleware.AppVersionMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = "project.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "mydatabase"),
        "USER": os.getenv("DB_USER", "mydatabaseuser"),
        "PASSWORD": os.getenv("DB_PASSWORD", "mypassword"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {
            "pool": {
                "min_size": int(os.getenv("DB_POOL_MIN_SIZE", "2")),
                "max_size": int(os.getenv("DB_POOL_MAX_SIZE", "10")),
                "timeout": int(os.getenv("DB_POOL_TIMEOUT_SECONDS", "10")),
            },
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # socket_timeout must exceed channels_redis brpop_timeout (5s).
            # redis-py 8.x default of 5s causes a race condition with BZPOPMIN.
            "hosts": [
                {
                    "address": os.getenv("REDIS_URL", "redis://localhost:6379"),
                    "socket_timeout": 30,
                    "socket_connect_timeout": 5,
                }
            ],
        },
    }
}

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
BOT_QUEUE_WAIT_SECONDS = int(os.getenv("BOT_QUEUE_WAIT_SECONDS", "8"))
DEBATE_BOT_USERNAME = os.getenv("DEBATE_BOT_USERNAME", "vaadvivaad_bot")

FIREBASE_CREDENTIALS_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH", "")

REDDIT_CLIENT_ID = os.getenv("REDDIT_CLIENT_ID", "")
REDDIT_CLIENT_SECRET = os.getenv("REDDIT_CLIENT_SECRET", "")
REDDIT_USER_AGENT = os.getenv("REDDIT_USER_AGENT", "")

GUARDIAN_API_KEY = os.getenv("GUARDIAN_API_KEY", "")

# Google OAuth settings
GOOGLE_OAUTH_CONFIG = {
    "GOOGLE_OAUTH_CLIENT_ID": os.getenv("GOOGLE_OAUTH_CLIENT_ID"),
    "GOOGLE_OAUTH_CLIENT_SECRET": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET"),
    "GOOGLE_OAUTH_CALLBACK_URL": os.getenv("GOOGLE_OAUTH_CALLBACK_URL"),
    "GOOGLE_AUTHORIZATION_URL": os.getenv("GOOGLE_AUTHORIZATION_URL"),
    "GOOGLE_ACCESS_TOKEN_OBTAIN_URL": os.getenv("GOOGLE_ACCESS_TOKEN_OBTAIN_URL"),
    "GOOGLE_USER_INFO_URL": os.getenv("GOOGLE_USER_INFO_URL"),
    "GOOGLE_ID_TOKEN_INFO_URL": os.getenv("GOOGLE_ID_TOKEN_INFO_URL"),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=24 * 60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
}

UNFOLD = {
    "SITE_TITLE": "Vaad Vivaad",
    "SITE_HEADER": "Vaad Vivaad Admin",
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
    },
}

# Celery — broker: RabbitMQ (see docker-compose). Override via CELERY_BROKER_URL.
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL", "amqp://guest:guest@127.0.0.1:5672//"
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "rpc://")
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_EXCHANGE = task_default_exchange
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = task_default_exchange_type
CELERY_TASK_DEFAULT_ROUTING_KEY = task_default_routing_key
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_QUEUES = task_queues
CELERY_TASK_ROUTES = task_routes
# Celery hijacks the root logger by default and applies its own colorized
# formatter, overriding Django's LOGGING config for the worker process.
# Disable it so celery_worker logs use the same format as the api process.
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {module} {funcName} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
}
